---
kind: pipeline
type: docker
name: gcc_build

steps:
  - name: lint
    image: vesoft/nebula-dev:centos7
    commands:
      - mkdir -p build && cd build
      - cmake ..
      - make format
      - git diff --exit-code
      - cd .. && rm -rf build

  - name: gcc_build
    image: vesoft/nebula-dev:centos7
    commands:
      - mkdir build && cd build
      - cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=on ..
      - make -j $(nproc)
      - ctest -j $(nproc) --timeout 400 --output-on-failure
    depends_on:
      - lint

---
kind: pipeline
type: docker
name: clang_build

steps:
  - name: lint
    image: vesoft/nebula-dev:ubuntu1804
    commands:
      - mkdir -p build && cd build
      - cmake ..
      - make format
      - git diff --exit-code
      - cd .. && rm -rf build

  - name: clang_build
    image: vesoft/nebula-dev:ubuntu1804
    commands:
      - mkdir build && cd build
      - cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Debug -DENABLE_ASAN=on -DENABLE_TESTING=on ..
      - make -j $(nproc)
      - ctest -j $(nproc) --timeout 400 --output-on-failure
    depends_on:
      - lint
